/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_PROXY_HPP_
#define V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_PROXY_HPP_

#include <v1/genivi/aasr/showcase/IDrivingLaneProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace genivi {
namespace aasr {
namespace showcase {

template <typename ... _AttributeExtensions>
class IDrivingLaneProxy
    : virtual public IDrivingLane,
      virtual public IDrivingLaneProxyBase,
      virtual public _AttributeExtensions... {
public:
    IDrivingLaneProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~IDrivingLaneProxy();

    typedef IDrivingLane InterfaceType;



    /**
     * Returns the wrapper class that provides access to the broadcast LaneDetected.
     */
    virtual LaneDetectedEvent& getLaneDetectedEvent() {
        return delegate_->getLaneDetectedEvent();
    }



    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr< IDrivingLaneProxyBase> delegate_;
};

typedef IDrivingLaneProxy<> IDrivingLaneProxyDefault;


//
// IDrivingLaneProxy Implementation
//
template <typename ... _AttributeExtensions>
IDrivingLaneProxy<_AttributeExtensions...>::IDrivingLaneProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< IDrivingLaneProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< IDrivingLaneProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
IDrivingLaneProxy<_AttributeExtensions...>::~IDrivingLaneProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &IDrivingLaneProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool IDrivingLaneProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool IDrivingLaneProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& IDrivingLaneProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& IDrivingLaneProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace showcase
} // namespace aasr
} // namespace genivi
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_PROXY_HPP_
