/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_STUB_HPP_
#define V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/genivi/aasr/showcase/IDrivingLane.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace genivi {
namespace aasr {
namespace showcase {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service IDrivingLane. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class IDrivingLaneStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual IDrivingLane {
 public:

    /**
    * Sends a broadcast event for LaneDetected. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireLaneDetectedEvent(const ::v1::genivi::aasr::showcase::IDrivingLane::LaneType &_drivingLane) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for IDrivingLane.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class IDrivingLaneStubRemoteEvent
{
public:
    virtual ~IDrivingLaneStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service IDrivingLane to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class IDrivingLaneStub
    : public virtual CommonAPI::Stub<IDrivingLaneStubAdapter, IDrivingLaneStubRemoteEvent>
{
public:

    virtual ~IDrivingLaneStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }


    /// Sends a broadcast event for LaneDetected.
    virtual void fireLaneDetectedEvent(const ::v1::genivi::aasr::showcase::IDrivingLane::LaneType &_drivingLane) {
        auto stubAdapter = CommonAPI::Stub<IDrivingLaneStubAdapter, IDrivingLaneStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireLaneDetectedEvent(_drivingLane);
    }

    
    using CommonAPI::Stub<IDrivingLaneStubAdapter, IDrivingLaneStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<IDrivingLaneStubAdapter, IDrivingLaneStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<IDrivingLaneStubAdapter, IDrivingLaneStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef IDrivingLaneStubRemoteEvent RemoteEventType;
    typedef IDrivingLane StubInterface;
};

} // namespace showcase
} // namespace aasr
} // namespace genivi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_GENIVI_AASR_SHOWCASE_I_Driving_Lane_STUB_HPP_
