/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201801251434.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/genivi/aasr/showcase/IDrivingLaneSomeIPDeployment.hpp>

namespace v1 {
namespace genivi {
namespace aasr {
namespace showcase {
namespace IDrivingLane_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace IDrivingLane_
} // namespace showcase
} // namespace aasr
} // namespace genivi
} // namespace v1
