/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GENIVI_AASR_SHOWCASE_I_DRIVING_LANE_INSTANCE_HPP_
#define V1_GENIVI_AASR_SHOWCASE_I_DRIVING_LANE_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace genivi {
namespace aasr {
namespace showcase {

const char * const IDrivingLane_drivinglane = "drivinglane";

const std::string IDrivingLane_INSTANCES[] = {
    IDrivingLane_drivinglane
};

} // namespace showcase
} // namespace aasr
} // namespace genivi
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_GENIVI_AASR_SHOWCASE_I_DRIVING_LANE_INSTANCE_HPP_
